#!/bin/bash
# Black Diamond Launcher
red() {
  printf '\e[1;31m%s\n\e[0;39;49m' "$@"
}

green() {
  printf '\e[1;32m%s\n\e[0;39;49m' "$@"
}
yellow() {
  printf '\e[1;33m%s\n\e[0;39;49m' "$@"
}
tgcli_version="180329-nightly"
luarocks_version=2.4.2
lualibs=(
'luasec'
'luarepl'
'lbase64 20120807-3'
'luafilesystem'
'lub'
'luaexpat'
'redis-lua'
'lua-cjson'
'fakeredis'
'xml'
'feedparser'
'serpent'
)

today=`data +%F`
installp() {
sudo apt-get update 
sudo apt-get upgrade
sudo apt-get install git redis-server lua5.2 liblua5.2-dev lua-lgi libnotify-dev unzip tmux -y && add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update 
sudo apt-get upgrade 
sudo apt-get install libconfig++9v5 libstdc++6 
sudo apt autoremove
sudo apt-get install gcc-4.9
sudo apt-get --yes install wget libconfig9 libjansson4 lua5.2 liblua5.2 make unzip git redis-server g++ whois fortune fortunes
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get install g++-4.7 -y c++-4.7 -y
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install libreadline-dev -y libconfig-dev -y libssl-dev -y lua5.2 -y liblua5.2-dev -y lua-socket -y lua-sec -y lua-expat -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y
sudo apt-get install screen -y
sudo apt-get install tmux -y
sudo apt-get install libstdc++6 -y
sudo apt-get install lua-lgi -y
sudo apt-get install libnotify-dev -y
sudo apt install libconfig++9v5
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9
sudo apt-get upgrade libstdc++6
sudo apt-get install libcurl-dev
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install libcurl4-gnutls-dev
wget http://luarocks.org/releases/luarocks-2.2.2.tar.gz;tar zxpf luarocks-2.2.2.tar.gz;cd luarocks-2.2.2 && ./configure; sudo make bootstrap;sudo luarocks install luasocket;sudo luarocks install luasec;sudo luarocks install redis-lua;sudo luarocks install lua-term;sudo luarocks install serpent;sudo luarocks install dkjson;sudo luarocks install lanes;sudo luarocks install Lua-cURL
}
get_sub() {
local flag=false c count cr=$'\r' nl=$'\n'
while IFS='' read -d '' -rn 1 c; do
 if $flag; then
 printf '%c' "$c"
  else
if [[ $c != $cr && $c != $nl ]]; then
  count=0
 else
((count++))
 if ((count > 1)); then
flag=true
fi
fi
fi
 done
}
make_progress() {
exe=`lua <<-EOF
    print(tonumber($1)/tonumber($2)*100)
EOF
`
    echo ${exe:0:4}
}
 get_tgcli_version() {
	echo "$tgcli_version"
}
 download_libs_lua() {
    if [[ ! -d "logs" ]]; then mkdir logs; fi
    if [[ -f "logs/logluarocks_${today}.txt" ]]; then rm logs/logluarocks_${today}.txt; fi
    local i
    for ((i=0;i<${#lualibs[@]};i++)); do
        printf "\r\33[2K"
        printf "\r• Installing Luarocks: wait... [`make_progress $(($i+1)) ${#lualibs[@]}`%%] [$(($i+1))/${#lualibs[@]}] ${lualibs[$i]}"
        ./.luarocks/bin/luarocks install ${lualibs[$i]} &>> logs/logluarocks_${today}.txt
    done
printf "\n• Logfile created: $PWD/logs/logluarocks_${today}.txt\nDone\n"
rm -rf luarocks-2.2.2*
}
startbotlogo() {
sleep 1
clear
red "ＢｌａｃｋＤｉａｍｏｎｄ   Ｓｏｕｒｃｅ"
echo "███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒10%"
sleep 0.3
yellow "██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒20%"
sleep 0.3
echo "█████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒30%"
sleep 0.3
yellow "████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒40%"
sleep 0.3
echo "███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒50%"
sleep 0.3
yellow "██████████████████▒▒▒▒▒▒▒▒▒▒▒▒60%"
sleep 0.3
echo "█████████████████████▒▒▒▒▒▒▒▒▒70%"
sleep 0.3
yellow "████████████████████████▒▒▒▒▒▒80%"
sleep 0.3
echo "███████████████████████████▒▒▒90%"
 sleep 0.6
green "██████████████████████████████100%"
}

chmodtelegram() {
echo "Done! > For Launch Cli : screen ./bd cli"
}
 configtime() {
 cd ..
 sudo cp /usr/share/zoneinfo/Asia/Tehran /etc/localtime
 sudo apt install libconfig++9v5
 sudo apt-get install lua-lgi
 sudo apt-get install libnotify-dev
 sudo apt install speedtest-cli
  cd saeed
}
 config() {
    dir=$PWD
    wget http://luarocks.org/releases/luarocks-${luarocks_version}.tar.gz &>/dev/null
    tar zxpf luarocks-${luarocks_version}.tar.gz &>/dev/null
    cd luarocks-${luarocks_version}
    if [[ ${1} == "--no-null" ]]; then
        ./configure --prefix=$dir/.luarocks --sysconfdir=$dir/.luarocks/luarocks --force-config
        make bootstrap
    else
./configure --prefix=$dir/.luarocks --sysconfdir=$dir/.luarocks/luarocks --force-config &>/dev/null
make bootstrap &>/dev/null
fi
cd ..
if [[ ${1} != "--no-download" ]]; then
download_libs_lua
cd $HOME
 cd saeed
sudo chmod +x  saeed/JokerApi.lua
fi
for ((i=0;i<101;i++)); do
printf "\rConfiguring... [%i%%]" $i
sleep 0.007
done
sudo rm -rf luarocks*
sudo rm -rf .luarocks
sudo rm -rf logs
printf "\nDone\nFor Login : ./bd cli\nFor Run : screen ./bd autocli\n\n"
}

lhelper() {
lua5.3 JokerCle.lua
}

Autoc() {
COUNTER=1
while(true) do
lua5.3 JokerApi.lua
let COUNTER=COUNTER+1 
done
}

Autoa() {
COUNTER=1
while(true) do
lua5.3 JokerCle.lua
let COUNTER=COUNTER+1 
done
}

Autoh() {
 COUNTER=1
while(true) do
lua5.3 JokerBot.lua
let COUNTER=COUNTER+1 
done
}

screen() {
echo ""
echo ""
green "    >> Ｃｌｉ  Ｂｏｔ  Ｌａｕｎｃｈｅｄ !"
yellow "    Ɓσт Mѕgѕ :"
lua5.3 JokerCle.lua
}
screenapi() {
echo ""
echo ""
green "    >> A p i Ｂｏｔ   Ｌａｕｎｃｈｅｄ !"
yellow "    Ɓσт Mѕgѕ :"
lua5.3 JokerApi.lua
}

lcli() {
lua5.3 JokerCle.lua
} 

lapi() {
lua5.3 JokerApi.lua
}
function gitpull() {
git checkout bd  bot/ libs/
git pull
echo chmod +x bd | /bin/bash
version=$(echo "./bd tgcli_version" | /bin/bash)
updateTD $version
}

CONFIG() {
TXT=(
"Installing Bot"
)
printf "${TXT}"
printf "\n"
}
warning() {
echo "Your Command Not Found!"
echo "Use The Following Commands :"
echo "install ➜ نصب سورس"
echo "cli ➜ Cli راه اندازی ربات "
echo "helper ➜ راه اندازی ربات هلپر"
echo "api ➜ Api راه اندازی ربات "
echo "autocli ➜ Cli اتولانچ ربات "
echo "autoapi ➜ Api اتولانچ ربات "
echo "autohelper ➜ اتولانچ ربات هلپر"
echo "installp ➜ نصب پکیج های مورد نیاز سرور لینوکس"
}
case $1 in
install)
configtime
CONFIG
config ${2}
exit ;;
installp)
installp
exit;;
cli)
startbotlogo
screen
exit;;
api)
startbotlogo
screenapi
exit;;
helper)
lhelper
exit;;
autocli)
Autoc
red "Start Auto Launch Cli...."
startbotlogo
echo ""
green "    >> Ａｕｔｏ  Ｌａｕｎｃｈ  Ｓｔａｒｔｅｄ !"
yellow "    Ɓσт Mѕgѕ :"
exit;;
autoapi)
red "Start Auto Launch Api...."
startbotlogo
echo ""
green "    >> Ａｕｔｏ  Ｌａｕｎｃｈ  Ｓｔａｒｔｅｄ !"
yellow "    Ɓσт Mѕgѕ :"
Autoa
exit;;
autohelper)
red "Start Auto Launch Helper...."
startbotlogo
Autoh
exit;;
autoall)
tmux kill-session -t "Cli"
tmux new-session -d -s "Cli" "./bd autocli"
tmux detach -s "Cli"
echo "Cli Running !"
sleep 2
tmux kill-session -t "Api"
tmux new-session -d -s "Api" "./bd autoapi"
tmux detach -s "Api"
echo "Api Running !"
sleep 2
tmux kill-session -t "Helper"
tmux new-session -d -s "Helper" "./bd autohelper"
tmux detach -s "Helper"
echo "Helper Running !"
exit;;
stopall)
tmux kill-session -t "Cli"
tmux kill-session -t "Api"
tmux kill-session -t "Helper"
red "Bot Is Off !"
exit;;
esac
warning
exit 0
 
