#!/bin/bash

#----functions-----------
#red
red() {
  printf '\e[1;31m%s\n\e[0;39;49m' "$@"
}
#green
green() {
  printf '\e[1;32m%s\n\e[0;39;49m' "$@"
}
#yellow
yellow() {
  printf '\e[1;33m%s\n\e[0;39;49m' "$@"
}
help() {
echo -e ""
echo -e ""
green ">>> Help Cmd RuBiTe :"
echo -e ""
echo -e ""
green ">>> ./run help : See this help"
echo -e ""
green ">>> ./run install : Install libs"
echo -e ""
green ">>> ./run loginapi : Login Bot Api"
echo -e ""
green ">>> ./run logincli : Login Bot Cli"
echo -e ""
green ">>> ./run launchapi : Launch Bot Api"
echo -e ""
green ">>> ./run launchcli : Launch Bot Cli"
echo -e ""
green ">>> ./run launchpanel : Launch Panel Bot"
echo -e ""
green ">>> ./run relaunchapi : Relaunch Bot Api"
echo -e ""
green ">>> ./run relaunchcli : Relaunch Bot Cli"
echo -e ""
green ">>> ./run relaunchpanel : Relaunch Panel Bot"
echo -e ""
green ">>> ./run stopapi : Stop Bot Api"
echo -e ""
green ">>> ./run stopcli : Stop Bot Cli"
echo -e ""
green ">>> ./run stopanel : Stop Panel Bot"
echo -e ""
green ">>> ./run launchbot : Launch Bot"
echo -e ""
green ">>> ./run stopbot : Stop Bot"
echo -e ""
green ">>> ./run launchallapi : LaunchAll Bot Api"
echo -e ""
green ">>> ./run launchallcli : LaunchAll Bot Cli"
echo -e ""
green ">>> ./run launchallpanel : LaunchAll Panel Bot"
echo -e ""
green ">>> ./run relaunchallapi : RelaunchAll Bot Api"
echo -e ""
green ">>> ./run relaunchallcli : RelaunchAll Bot Cli"
echo -e ""
green ">>> ./run relaunchallpanel : RelaunchAll Panel Bot"
echo -e ""
green ">>> ./run stopallapi : StopAll Bot Api"
echo -e ""
green ">>> ./run stopallcli : StopAll Bot Cli"
echo -e ""
green ">>> ./run stopallpanel : StopAll Panel Bot"
echo -e ""
green ">>> ./run launchallbot : LaunchAll Bot"
echo -e ""
green ">>> ./run launchallbot : RelaunchAll Bot"
echo -e ""
green ">>> ./run stopallbot : StopAll Bot"
echo -e ""
}
#------help-----------
if [ "$1" = "help" ]; then
help
exit 1
#------install-----------
elif [ "$1" = "install" ]; then
sudo apt-get update
sudo apt-get upgrade
sudo ip addr show
sudo apt-get install zip
sudo apt-get install unzip
sudo cp /usr/share/zoneinfo/Asia/Tehran /etc/localtime
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get install g++-4.7 -y c++-4.7 -y
sudo apt-get install libreadline-dev -y libconfig-dev -y libssl-dev -y lua5.2 -y liblua5.2-dev -y lua-socket -y lua-sec -y lua-expat -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y
sudo apt-get install screen -y
sudo apt-get install tmux -y
sudo apt-get install toilet -y
sudo apt-get install libstdc++6 -y
sudo apt-get install lua-lgi -y
sudo apt-get install libnotify-dev -y
sudo apt-get install lua5.1 luarocks lua-socket lua-sec redis-server curl 
cd ..
wget http://luarocks.org/releases/luarocks-2.2.2.tar.gz
tar zxpf luarocks-2.2.2.tar.gz
cd luarocks-2.2.2
./configure; sudo make bootstrap
sudo luarocks install luasocket
sudo luarocks install luasec
sudo luarocks install redis-lua
sudo luarocks install lua-term
sudo luarocks install serpent
sudo luarocks install dkjson
sudo luarocks install lanes
sudo luarocks install Lua-cURL
sudo luarocks install utf8
sudo luarocks install oauth 
sudo luarocks install lua-cjson 
sudo luarocks install ansicolors 
sudo apt-get install libstdc++9
sudo apt-get install libconfig++9v5 libstdc++6
sudo apt install git redis-server lua5.3 liblua5.3-dev lua-lgi libnotify-dev unzip tmux -y 
sudo apt install libconfig++9v5 libstdc++6
sudo apt autoremove
sudo apt install gcc-4.9
sudo apt --yes install wget libconfig9 libjansson4 liblua5.3 make unzip g++ whois fortune fortunes
sudo apt install g++-4.7 -y c++-4.7 -y
sudo apt install libreadline-dev -y libconfig-dev - y libssl-dev -y lua5.3 -y liblua5.3-dev -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y
sudo apt install screen -y
sudo apt-get update
sudo apt-get upgrade
cd ..
wget https://luarocks.org/releases/luarocks-3.3.0.tar.gz
tar zxpf luarocks-3.3.0.tar.gz
cd luarocks-3.3.0
./configure && make && sudo make install
./configure --lua-version=5.3
make build
sudo make install
cd ..
sudo luarocks install dkjson
sudo luarocks install redis-lua
sudo luarocks install serpent 
sudo luarocks install luasocket
sudo luarocks install luasec
sudo luarocks install lua-sec
sudo luarocks remove lua-cjson
sudo luarocks install lua-cjson 2.1.0-1
cd /usr/src
wget 'https://www.openssl.org/source/openssl-1.1.1f.tar.gz'
tar -zxf openssl-1.1.1f.tar.gz
cd openssl-1.1.1f
./config
make
make test
make install
export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64
sudo ldconfig
green ">> All Packages Were Successfully Installed !"
#------loginapi-----------
elif [ "$1" = "loginapi" ]; then
if [ -z "$2" ]; then
  green "Enter Your Bot-number :" 
  read -rp ' ' BotNumber
else
  BotNumber=$2
fi
for entr in "./ConfigAll"/*
do
Id="${entr/.\/ConfigAll\/Config-/}"
  if [ ${Id} = $BotNumber".lua" ]; then
    botrun=true
    break
  fi
done
if [ -z "$botrun" ]; then
  lua5.3 bot.lua $BotNumber
else
  red "Bot-number {$BotNumber} is Login"
  lua5.3 bot.lua $BotNumber
fi
#------installcli-----------
elif [ "$1" = "logincli" ]; then
if [ -z "$2" ]; then
  green "Enter Your Bot-number :" 
  read -rp ' ' BotNumber
else
  BotNumber=$2
fi
for entr in "./ConfigAll"/*
do
Id="${entr/.\/ConfigAll\/Config-/}"
  if [ ${Id} = $BotNumber".lua" ]; then
    botrun=true
    break
  fi
done
if [ -z "$botrun" ]; then
  lua5.3 cli.lua $BotNumber
else
  red "Bot-number {$BotNumber} is Login"
  lua5.3 cli.lua $BotNumber
fi
#------launchapi-----------
elif [ "$1" = "launchapi" ]; then
if [ -z "$2" ]; then
  green "Enter Your Bot-number :" 
  read -rp ' ' BotNumber
else
  BotNumber=$2
fi
tmux new-session -d -s  BotProAdd-Api${BotNumber} "./apiauto.sh "${BotNumber}
green "BotApi-number {${BotNumber}} Raning"
#------launchscript-----------
elif [ "$1" = "launchscript" ]; then
tmux new-session -d -s  ScriptBotProAdd "./script-auto.sh"
green "Script ZedlinkPro Raning" 
#------stopscript-----------
elif [ "$1" = "stopscript" ]; then
tmux kill-session -t  ScriptBotProAdd
red "Script ZedlinkPro Stoping" 
#------launchcli-----------
elif [ "$1" = "launchcli" ]; then
if [ -z "$2" ]; then
  green "Enter Your Bot-number :" 
  read -rp ' ' BotNumber
else
  BotNumber=$2
fi
tmux new-session -d -s  BotProAdd-Cli${BotNumber} "./cliauto.sh "${BotNumber}
green "BotCli-number {${BotNumber}} Raning" 
#------launchpanel-----------
elif [ "$1" = "launchpanel" ]; then
if [ -z "$2" ]; then
  green "Enter Your Bot-number :" 
  read -rp ' ' BotNumber
else
  BotNumber=$2
fi
tmux new-session -d -s  BotProAdd-Panel${BotNumber} "./helperauto.sh "${BotNumber}
green "PanelBot-number {${BotNumber}} Raning" 
#------relaunchapi-----------
elif [ "$1" = "relaunchapi" ]; then
if [ -z "$2" ]; then
  green "Enter Your Bot-number :" 
  read -rp ' ' BotNumber
else
  BotNumber=$2
fi
tmux kill-session -t  BotProAdd-Api${BotNumber}
red "BotApi-number {${BotNumber}} Stoping" 
tmux new-session -d -s  BotProAdd-Api${BotNumber} "./apiauto.sh "${BotNumber}
green "BotApi-number {${BotNumber}} Raning" 
#------relaunchcli-----------
elif [ "$1" = "relaunchcli" ]; then
if [ -z "$2" ]; then
  green "Enter Your Bot-number :" 
  read -rp ' ' BotNumber
else
  BotNumber=$2
fi
tmux kill-session -t  BotProAdd-Cli${BotNumber}
red "BotCli-number {${BotNumber}} Stoping" 
tmux new-session -d -s  BotProAdd-Cli${BotNumber} "./cliauto.sh "${BotNumber}
green "BotCli-number {${BotNumber}} Raning" 
#------relaunchpanel-----------
elif [ "$1" = "relaunchpanel" ]; then
if [ -z "$2" ]; then
  green "Enter Your Bot-number :" 
  read -rp ' ' BotNumber
else
  BotNumber=$2
fi
tmux kill-session -t  BotProAdd-Panel${BotNumber}
red "PanelBot-number {${BotNumber}} Stoping" 
tmux new-session -d -s  BotProAdd-Panel${BotNumber} "./helperauto.sh "${BotNumber}
green "PanelBot-number {${BotNumber}} Raning" 
#------stopapi-----------
elif [ "$1" = "stopapi" ]; then
if [ -z "$2" ]; then
  green "Enter Your Bot-number :" 
  read -rp ' ' BotNumber
else
  BotNumber=$2
fi
tmux kill-session -t  BotProAdd-Api${BotNumber}
red "BotApi-number {${BotNumber}} Stoping" 
#------stopcli-----------
elif [ "$1" = "stopcli" ]; then
if [ -z "$2" ]; then
  green "Enter Your Bot-number :" 
  read -rp ' ' BotNumber
else
  BotNumber=$2
fi
tmux kill-session -t  BotProAdd-Cli${BotNumber}
red "BotCli-number {${BotNumber}} Stoping" 
#------stoppanel-----------
elif [ "$1" = "stoppanel" ]; then
if [ -z "$2" ]; then
  green "Enter Your Bot-number :" 
  read -rp ' ' BotNumber
else
  BotNumber=$2
fi
tmux kill-session -t  BotProAdd-Panel${BotNumber}
red "PanelBot-number {${BotNumber}} Stoping" 
#------launchbot-----------
elif [ "$1" = "launchbot" ]; then
if [ -z "$2" ]; then
  green "Enter Your Bot-number :" 
  read -rp ' ' BotNumber
else
  BotNumber=$2
fi
tmux new-session -d -s  BotProAdd-Api${BotNumber} "./apiauto.sh "${BotNumber}
tmux new-session -d -s  BotProAdd-Cli${BotNumber} "./cliauto.sh "${BotNumber}
tmux new-session -d -s  BotProAdd-Panel${BotNumber} "./helperauto.sh "${BotNumber}
green "Bot-number {${BotNumber}} Raning" 
#------relaunchbot-----------
elif [ "$1" = "relaunchbot" ]; then
if [ -z "$2" ]; then
  green "Enter Your Bot-number :" 
  read -rp ' ' BotNumber
else
  BotNumber=$2
fi
tmux kill-session -t  BotProAdd-Api${BotNumber}
tmux kill-session -t  BotProAdd-Panel${BotNumber}
tmux kill-session -t  BotProAdd-Cli${BotNumber}
red "Bot-number {${BotNumber}} Stoping"
tmux new-session -d -s  BotProAdd-Api${BotNumber} "./apiauto.sh "${BotNumber}
tmux new-session -d -s  BotProAdd-Cli${BotNumber} "./cliauto.sh "${BotNumber}
tmux new-session -d -s  BotProAdd-Panel${BotNumber} "./helperauto.sh "${BotNumber}
green "Bot-number {${BotNumber}} Raning" 
#------stopbot-----------
elif [ "$1" = "stopbot" ]; then
if [ -z "$2" ]; then
  green "Enter Your Bot-number :" 
  read -rp ' ' BotNumber
else
  BotNumber=$2
fi
tmux kill-session -t  BotProAdd-Api${BotNumber}
tmux kill-session -t  BotProAdd-Panel${BotNumber}
tmux kill-session -t  BotProAdd-Cli${BotNumber}
red "Bot-number {${BotNumber}} Stoping"
#------launchallapi-----------
elif [ "$1" = "launchallapi" ]; then
  for entr in "./ConfigAll"/*; do
    Id="${entr//[^0-9]/}"
    tmux new-session -d -s  BotProAdd-Api${Id} "./apiauto.sh "${Id}
    green "BotApi-number {${Id}} Raning" 
    sleep 1
  done
#------launchallcli-----------
elif [ "$1" = "launchallcli" ]; then
  for entr in "./ConfigAll"/*; do
    Id="${entr//[^0-9]/}"
    tmux new-session -d -s  BotProAdd-Cli${Id} "./cliauto.sh "${Id}
    green "BotCli-number {${Id}} Raning" 
    sleep 1
  done
#------launchallpanel-----------
elif [ "$1" = "launchallpanel" ]; then
  for entr in "./ConfigAll"/*; do
    Id="${entr//[^0-9]/}"
    tmux new-session -d -s  BotProAdd-Panel${Id} "./helperauto.sh "${Id}
    green "PanelBot-number {${Id}} Raning" 
    sleep 1
  done
#------relaunchallapi-----------
elif [ "$1" = "relaunchallapi" ]; then
  for entr in "./ConfigAll"/*; do
    Id="${entr//[^0-9]/}"
    tmux kill-session -t  BotProAdd-Api${Id}
    red "BotApi-number {${Id}} Stoping" 
    tmux new-session -d -s  BotProAdd-Api${Id} "./apiauto.sh "${Id}
    green "BotApi-number {${Id}} Raning" 
    sleep 1
  done
#------relaunchallcli-----------
elif [ "$1" = "relaunchallcli" ]; then
  for entr in "./ConfigAll"/*; do
    Id="${entr//[^0-9]/}"
    tmux kill-session -t  BotProAdd-Cli${Id}
    red "BotCli-number {${Id}} Stoping" 
    tmux new-session -d -s  BotProAdd-Cli${Id} "./cliauto.sh "${Id}
    green "BotCli-number {${Id}} Raning" 
    sleep 1
  done
#------relaunchallpanel-----------
elif [ "$1" = "relaunchallpanel" ]; then
  for entr in "./ConfigAll"/*; do
    Id="${entr//[^0-9]/}"
    tmux kill-session -t  BotProAdd-Panel${Id}
    red "PanelBot-number {${Id}} Stoping" 
    tmux new-session -d -s  BotProAdd-Panel${Id} "./helperauto.sh "${Id}
    green "PanelBot-number {${Id}} Raning" 
    sleep 1
  done
#------stopallapi-----------
elif [ "$1" = "stopallapi" ]; then
  for entr in "./ConfigAll"/*; do
    Id="${entr//[^0-9]/}"
    tmux kill-session -t  BotProAdd-Api${Id}
    red "BotApi-number {${Id}} Stoping" 
    sleep 1
  done
#------stopallcli-----------
elif [ "$1" = "stopallcli" ]; then
  for entr in "./ConfigAll"/*; do
    Id="${entr//[^0-9]/}"
    tmux kill-session -t  BotProAdd-Cli${Id}
    red "BotCli-number {${Id}} Stoping" 
    sleep 1
  done
#------stopallpanel-----------
elif [ "$1" = "stopallpanel" ]; then
  for entr in "./ConfigAll"/*; do
    Id="${entr//[^0-9]/}"
    tmux kill-session -t  BotProAdd-Panel${Id}
    red "PanelBot-number {${Id}} Stoping" 
    sleep 1
  done
#------launchallbot-----------
elif [ "$1" = "launchallbot" ]; then
  for entr in "./ConfigAll"/*; do
    Id="${entr//[^0-9]/}"
    tmux new-session -d -s  BotProAdd-Api${Id} "./apiauto.sh "${Id}
    tmux new-session -d -s  BotProAdd-Cli${Id} "./cliauto.sh "${Id}
    tmux new-session -d -s  BotProAdd-Panel${Id} "./helperauto.sh "${Id}
    green "Bot-number {${Id}} Raning" 
    sleep 1
  done
#------relaunchallbot-----------
elif [ "$1" = "relaunchallbot" ]; then
  for entr in "./ConfigAll"/*; do
    Id="${entr//[^0-9]/}"
    tmux kill-session -t  BotProAdd-Api${Id}
    tmux kill-session -t  BotProAdd-Panel${Id}
    tmux kill-session -t  BotProAdd-Cli${Id}
    red "Bot-number {${Id}} Stoping" 
    tmux new-session -d -s  BotProAdd-Api${Id} "./apiauto.sh "${Id}
    tmux new-session -d -s  BotProAdd-Cli${Id} "./cliauto.sh "${Id}
    tmux new-session -d -s  BotProAdd-Panel${Id} "./helperauto.sh "${Id}
    green "Bot-number {${Id}} Raning" 
    sleep 1
  done
#------stopallbot-----------
elif [ "$1" = "stopallbot" ]; then
  for entr in "./ConfigAll"/*; do
    Id="${entr//[^0-9]/}"
    tmux kill-session -t  BotProAdd-Api${Id}
    tmux kill-session -t  BotProAdd-Panel${Id}
    tmux kill-session -t  BotProAdd-Cli${Id}
    red "Bot-number {${Id}} Stoping" 
    sleep 1
  done
else
help
fi